version: '3.8'

volumes:
  db-data:


services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/book-register'
    environment:
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15.1
    volumes:
      - 'db-data:/var/lib/postgres/data'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
